/**
 * @file runtime_manager.hpp
 * @brief Unity runtime translation system (BepInEx + XUnity)
 * @copyright (c) 2026 MakineAI Team
 *
 * Manages installation and configuration of the MakineAI Translation System
 * for Unity games. This embeds BepInEx and XUnity.AutoTranslator within
 * MakineAI, branded as "MakineAI Translation System".
 */

#pragma once

#include "types.hpp"
#include "error.hpp"

#include <memory>

namespace makineai {

/**
 * @brief Unity scripting backend type
 */
enum class UnityBackend {
    Unknown,
    Mono,       // Classic Unity with Mono (uses BepInEx 5.x)
    IL2CPP      // Unity IL2CPP (uses BepInEx 6.x)
};

/**
 * @brief Runtime component versions
 */
struct RuntimeVersion {
    Version bepinex;
    Version xunity;
    Version makineaiPlugin;

    bool operator==(const RuntimeVersion&) const = default;
    auto operator<=>(const RuntimeVersion&) const = default;
};

/**
 * @brief Runtime installation status
 */
struct RuntimeStatus {
    bool installed;
    bool upToDate;
    RuntimeVersion installedVersion;
    RuntimeVersion bundledVersion;
    UnityBackend backend;
    fs::path installPath;
    StringList translationFiles;
};

/**
 * @brief XUnity.AutoTranslator configuration
 */
struct XUnityConfig {
    std::string endpoint = "MakineAI";  // Translation endpoint (shows in logs)
    bool enableAutoTranslation = false;  // We use pre-made translations
    bool enableTextureTranslation = true;
    bool enableUGUIHooking = true;
    bool enableIMGUIHooking = true;
    bool enableNGUIHooking = true;
    bool enableTextMeshProHooking = true;
    std::string outputFile = "_AutoGeneratedTranslations.txt";
    std::string translationsDirectory = "Translation";
};

/**
 * @brief Manages runtime translation for Unity games
 */
class RuntimeManager {
public:
    RuntimeManager();
    ~RuntimeManager();

    /**
     * @brief Check if game needs runtime translation
     *
     * Unity games need runtime because binary patching corrupts assets.
     */
    [[nodiscard]] bool needsRuntime(const GameInfo& game) const;

    /**
     * @brief Detect Unity backend type
     */
    [[nodiscard]] UnityBackend detectBackend(const fs::path& gameDir) const;

    /**
     * @brief Check runtime installation status
     */
    [[nodiscard]] Result<RuntimeStatus> checkStatus(const GameInfo& game) const;

    /**
     * @brief Install runtime to game
     *
     * Installs BepInEx + XUnity.AutoTranslator configured for MakineAI.
     */
    [[nodiscard]] VoidResult install(
        const GameInfo& game,
        ProgressCallback progress = nullptr
    );

    /**
     * @brief Update runtime to latest bundled version
     */
    [[nodiscard]] VoidResult update(
        const GameInfo& game,
        ProgressCallback progress = nullptr
    );

    /**
     * @brief Uninstall runtime from game
     */
    [[nodiscard]] VoidResult uninstall(const GameInfo& game);

    /**
     * @brief Add translation files to game
     *
     * Copies translation files to the appropriate directory
     * for XUnity.AutoTranslator to load.
     */
    [[nodiscard]] VoidResult addTranslations(
        const GameInfo& game,
        const fs::path& translationDir
    );

    /**
     * @brief Remove translation files from game
     */
    [[nodiscard]] VoidResult removeTranslations(const GameInfo& game);

    /**
     * @brief Get path to runtime bundle directory
     */
    [[nodiscard]] fs::path bundleDirectory() const { return bundleDir_; }

    /**
     * @brief Set runtime bundle directory
     */
    void setBundleDirectory(const fs::path& dir) { bundleDir_ = dir; }

    /**
     * @brief Get bundled runtime version
     */
    [[nodiscard]] RuntimeVersion bundledVersion() const;

    /**
     * @brief Configure XUnity settings for a game
     */
    [[nodiscard]] VoidResult configureXUnity(
        const GameInfo& game,
        const XUnityConfig& config = XUnityConfig{}
    );

    /**
     * @brief Validate that bundle directory has all required files
     *
     * Checks for BepInEx core DLLs, doorstop files, and XUnity plugin
     * for the specified backend type.
     *
     * @param backend Mono or IL2CPP
     * @return Error listing missing files if validation fails
     */
    [[nodiscard]] VoidResult validateBundle(UnityBackend backend) const;

    /**
     * @brief GitHub release info for BepInEx
     */
    struct ReleaseInfo {
        std::string tagName;
        std::string downloadUrl;
        std::string assetName;
        uint64_t size = 0;
    };

    /**
     * @brief Fetch latest BepInEx release info from GitHub
     *
     * Queries GitHub Releases API for the latest stable release.
     *
     * @param backend Mono (BepInEx 5.x) or IL2CPP (BepInEx 6.x)
     * @return Release info with download URL
     */
    [[nodiscard]] Result<ReleaseInfo> fetchLatestRelease(UnityBackend backend) const;

private:
    fs::path bundleDir_;

    // Bundle structure paths
    fs::path getMonoBundlePath() const;
    fs::path getIL2CPPBundlePath() const;

    // Installation helpers
    [[nodiscard]] VoidResult installMono(const GameInfo& game, ProgressCallback progress);
    [[nodiscard]] VoidResult installIL2CPP(const GameInfo& game, ProgressCallback progress);
    [[nodiscard]] VoidResult writeXUnityConfig(const fs::path& gameDir, const XUnityConfig& config);
};

/**
 * @brief Unity game analysis result
 */
struct UnityAnalysis {
    bool isUnity;
    UnityBackend backend;
    std::string unityVersion;
    bool is64Bit;
    fs::path dataDirectory;     // xxx_Data folder
    fs::path managedDirectory;  // Managed DLLs
    bool hasExistingBepInEx;
};

/**
 * @brief Analyze Unity game installation
 */
[[nodiscard]] Result<UnityAnalysis> analyzeUnityGame(const fs::path& gameDir);

} // namespace makineai
